// Generated by CoffeeScript 1.7.1
if (window.Rrs == null) {
  window.Rrs = {};
}

Rrs.Observer = (function() {
  var instance;

  instance = null;

  Observer.instance = function() {
    return instance != null ? instance : instance = new Rrs.Observer;
  };

  function Observer() {
    this._listeners = {};
  }

  Observer.prototype.emit = function(inNamespace, inSignalName, inData) {
    var signal, _ref;
    signal = "" + inNamespace + ":" + inSignalName;
    Rrs.logger.debug("Emitting signal " + signal + ".", this._listeners);
    if (this._listeners[signal] != null) {
      return (_ref = this._listeners[signal].callback) != null ? _ref.call(this._listeners[signal].context, inData) : void 0;
    }
  };

  Observer.prototype.listen = function(inNamespace, inSignalName, callback, context) {
    var signal;
    signal = "" + inNamespace + ":" + inSignalName;
    Rrs.logger.debug("Attaching listener to " + signal + " signal.", this._listeners);
    return this._listeners[signal] = {
      callback: callback,
      context: context
    };
  };

  return Observer;

})();
