// Generated by CoffeeScript 1.7.1
var PageModule;

PageModule = (function() {
  var _props;

  _props = {};

  function PageModule(inProps) {
    var cmp, cmpName, _ref;
    _props = inProps;
    this._checkEnv();
    if (this.components == null) {
      this.components = {};
    }
    if ((_props != null ? _props.components : void 0) != null) {
      jQuery.extend(this.components, _props.components);
    }
    _ref = this.components;
    for (cmpName in _ref) {
      cmp = _ref[cmpName];
      if (cmp instanceof PageComponent) {
        cmp.init();
      } else {
        Rrs.logger.error("" + (cmp.toString()) + " is not an instance of PageComponent");
      }
    }
  }

  PageModule.create = function(inProps) {
    var className;
    className = Rrs.Obj.getClass(this);
    return new window[className](inProps);
  };

  PageModule.prototype._checkEnv = function() {
    if (typeof PageComponent === "undefined" || PageComponent === null) {
      throw new Error("PageComponent is not defined");
    }
  };

  return PageModule;

})();
