// Generated by CoffeeScript 1.7.1
var B, D, InvalidSelectorWidget, ResultWidget, SearchWidget, UserPanelWidget, setUpHTMLFixture,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.searchBtnClickHandler = function() {
  return 123;
};

window.resultWidgetRenderedListener = function() {
  return 456;
};

window.renderedListener = function() {
  return 456;
};

SearchWidget = (function(_super) {
  __extends(SearchWidget, _super);

  function SearchWidget() {
    return SearchWidget.__super__.constructor.apply(this, arguments);
  }

  SearchWidget.prototype.elements = {
    searchButton: $('#search-btn')
  };

  SearchWidget.prototype.handlers = {
    'searchButton click': searchBtnClickHandler
  };

  SearchWidget.prototype.listeners = {
    "ResultWidget:rendered": resultWidgetRenderedListener,
    "rendered": renderedListener
  };

  return SearchWidget;

})(Rrs.Component);

ResultWidget = (function(_super) {
  __extends(ResultWidget, _super);

  function ResultWidget() {
    return ResultWidget.__super__.constructor.apply(this, arguments);
  }

  ResultWidget.prototype.listeners = {
    "SearchWidget:render": function(data) {},
    "SearchWidget:hello": function(data) {}
  };

  return ResultWidget;

})(Rrs.Component);

UserPanelWidget = (function(_super) {
  __extends(UserPanelWidget, _super);

  function UserPanelWidget() {
    return UserPanelWidget.__super__.constructor.apply(this, arguments);
  }

  return UserPanelWidget;

})(Rrs.Component);

InvalidSelectorWidget = (function(_super) {
  __extends(InvalidSelectorWidget, _super);

  function InvalidSelectorWidget() {
    return InvalidSelectorWidget.__super__.constructor.apply(this, arguments);
  }

  InvalidSelectorWidget.prototype.elements = {
    someEl: '.el-class',
    searchButton: null
  };

  InvalidSelectorWidget.prototype.handlers = {
    'someEl click': function() {},
    'searchButton click': function() {}
  };

  return InvalidSelectorWidget;

})(Rrs.Component);

setUpHTMLFixture = function() {};

B = (function() {
  function B() {}

  B.prototype.test = function() {
    return console.error('^^^^^^^^^^^^^', this.p);
  };

  return B;

})();

D = (function() {
  function D() {}

  D.prototype.p = 1;

  return D;

})();

$(document).ready(function() {
  return new D;
});
