// Generated by CoffeeScript 1.7.1
describe("Rrs.Observer", function() {
  var observer;
  observer = null;
  beforeEach(function() {
    return observer = Rrs.Observer.instance();
  });
  it("implement the Singleton pattern", function() {
    var observer2;
    observer2 = Rrs.Observer.instance();
    return expect(observer).toEqual(observer2);
  });
  it("call subscribers callback and passed emitted data to it when namespace is used", function() {
    var cb, dataToBeSent;
    dataToBeSent = {
      key: 'val'
    };
    cb = function(data) {
      return expect(data).toEqual(dataToBeSent);
    };
    observer.listen('SomeNamespace', 'some-signal', cb, this);
    return observer.emit('SomeNamespace', 'some-signal', dataToBeSent);
  });
  it("bind observer to callers context when 'context' param is passed", function() {
    var cb, me;
    me = this;
    cb = function(data) {
      return expect(this).toEqual(me);
    };
    observer.listen('SomeNamespace', 'some-signal', cb, this);
    return observer.emit('SomeNamespace', 'some-signal');
  });
  it("throws exception when both namespace and signal are passed but context is not passed", function() {
    var cb, exception, signal;
    cb = function(data) {};
    signal = "SomeNamespace:some-signal";
    exception = new Error("Conext is not set for " + signal);
    return expect(function() {
      return observer.listen('SomeNamespace', 'some-signal', cb);
    }).toThrow(exception);
  });
  return it("throws exception when signal is passed but namespace and context are not passed", function() {
    var cb, exception, signal;
    cb = function(data) {};
    signal = "some-signal";
    exception = new Error("Conext is not set for " + signal);
    return expect(function() {
      return observer.listen(null, 'some-signal', cb);
    }).toThrow(exception);
  });
});
