// Generated by CoffeeScript 1.7.1
if (window.Rrs == null) {
  window.Rrs = {};
}

Rrs.Component = (function() {
  function Component() {}

  Component.prototype.init = function() {
    this._initHandlers();
    return this._initListeners();
  };

  Component.prototype.emit = function(inSignalName, inData) {
    var sender;
    sender = Rrs.Obj.getClass(this);
    return Rrs.Observer.instance().emit(sender, inSignalName, inData);
  };

  Component.prototype._initHandlers = function() {
    var element, elementName, eventName, handler, handlerData, handlerName, _ref, _results;
    _ref = this.handlers;
    _results = [];
    for (handlerName in _ref) {
      handler = _ref[handlerName];
      handlerData = handlerName.split(' ');
      elementName = handlerData[0];
      eventName = handlerData[1];
      element = this.elements[elementName];
      if (Rrs.Util.isString(element)) {
        element = jQuery(element);
      } else if (Rrs.Util.isJQeryObject(element)) {
        element = jQuery(element.selector);
      } else {
        throw new Error("" + elementName + " must be either string selector or jQuery object");
      }
      if (element.length > 0) {
        this.elements[elementName].unbind(eventName);
        _results.push(this.elements[elementName].bind(eventName, (function(_this) {
          return function() {
            return handler.call(_this);
          };
        })(this)));
      } else {
        _results.push(Rrs.logger.error("Unable to bind " + eventName + " for " + elementName + " since " + elementName + " node does not exist in DOM"));
      }
    }
    return _results;
  };

  Component.prototype._initListeners = function() {
    var listenerCallback, listenerName, listenerNameData, _ref, _results;
    _ref = this.listeners;
    _results = [];
    for (listenerName in _ref) {
      listenerCallback = _ref[listenerName];
      listenerNameData = listenerName.split(":");
      if ((listenerNameData != null) && ((listenerNameData.length === 1) || (listenerNameData.length === 2))) {
        if (listenerNameData.length === 1) {
          _results.push(Rrs.Observer.instance().listen(null, listenerNameData[0], listenerCallback, this));
        } else if (listenerNameData.length === 2) {
          _results.push(Rrs.Observer.instance().listen(listenerNameData[0], listenerNameData[1], listenerCallback, this));
        } else {
          _results.push(void 0);
        }
      } else {
        _results.push(Rrs.logger.error("Invalid listener format of name (" + listenerName + "). Must be Namespace:signal"));
      }
    }
    return _results;
  };

  return Component;

})();
